import json
import boto3
import os
from datetime import datetime, timedelta

# Initialize AWS clients
bedrock = boto3.client("bedrock-runtime", region_name=os.environ.get("AWS_REGION", "us-east-1"))
ses = boto3.client("ses", region_name=os.environ.get("AWS_REGION", "us-east-1"))
s3 = boto3.client("s3")

# Configuration from environment variables
BUCKET_NAME = os.environ["BUCKET_NAME"]          # S3 bucket for backlog items
EMAIL_TO = os.environ["EMAIL_TO"]                # Your email address
EMAIL_FROM = os.environ["EMAIL_FROM"]            # Verified SES sender email
MODEL_ID = os.environ.get("MODEL_ID", "amazon.nova-lite-v1:0")  # Bedrock model


def get_backlog_items():
    """Fetch backlog items from S3 (JSON file with tasks/notes)."""
    try:
        response = s3.get_object(Bucket=BUCKET_NAME, Key="backlog/items.json")
        items = json.loads(response["Body"].read().decode("utf-8"))
        return items
    except s3.exceptions.NoSuchKey:
        return []


def categorize_and_summarize(items):
    """Use Amazon Bedrock to categorize, prioritize, and summarize backlog items."""
    if not items:
        return "No backlog items found. Your slate is clean!"

    items_text = "\n".join(
        f"- [{item.get('status', 'open')}] {item.get('title', 'Untitled')}: "
        f"{item.get('description', 'No description')}"
        for item in items
    )

    prompt = (
        "You are a productivity assistant for a Product Manager.\n"
        "Analyze this backlog and produce a tidy morning-ready summary:\n\n"
        "BACKLOG ITEMS:\n"
        f"{items_text}\n\n"
        "Please:\n"
        "1. Categorize items into: Urgent, Needs Attention, Low Priority, Done/Closeable\n"
        "2. Identify stale items (no update in >7 days) and suggest closing or following up\n"
        "3. Summarize the top 3 things to focus on today\n"
        "4. Suggest items that can be archived or delegated\n\n"
        "Format as a clean, scannable email digest with emoji headers."
    )

    response = bedrock.invoke_model(
        modelId=MODEL_ID,
        body=json.dumps({
            "messages": [{"role": "user", "content": [{"text": prompt}]}],
            "inferenceConfig": {"maxTokens": 1024, "temperature": 0.3}
        }),
        contentType="application/json",
        accept="application/json"
    )

    result = json.loads(response["body"].read())
    return result["output"]["message"]["content"][0]["text"]


def save_sorted_backlog(items, summary):
    """Save the organized summary back to S3 for reference."""
    timestamp = datetime.now().strftime("%Y-%m-%d")
    s3.put_object(
        Bucket=BUCKET_NAME,
        Key=f"reports/{timestamp}-tidy-up.json",
        Body=json.dumps({
            "date": timestamp,
            "summary": summary,
            "item_count": len(items),
            "generated_at": datetime.now().isoformat()
        }),
        ContentType="application/json"
    )


def send_email(summary):
    """Send the tidy-up digest via Amazon SES."""
    today = datetime.now().strftime("%A, %B %d")

    html_body = (
        '<html><body style="font-family: -apple-system, sans-serif; '
        'max-width: 600px; margin: 0 auto; padding: 20px;">'
        '<h2 style="color: #232f3e;">Overnight Backlog Tidy-Up</h2>'
        '<p style="color: #666;">Your agent sorted through your backlog while you slept.</p>'
        '<hr style="border: 1px solid #eee;">'
        f'<div style="white-space: pre-wrap; line-height: 1.6;">{summary}</div>'
        '<hr style="border: 1px solid #eee;">'
        '<p style="color: #999; font-size: 12px;">'
        'Generated by your Overnight Tidy-Up Agent | '
        'Powered by Amazon Bedrock + EventBridge</p>'
        '</body></html>'
    )

    ses.send_email(
        Source=EMAIL_FROM,
        Destination={"ToAddresses": [EMAIL_TO]},
        Message={
            "Subject": {"Data": f"Your Backlog Tidy-Up - {today}"},
            "Body": {"Html": {"Data": html_body}}
        }
    )


def lambda_handler(event, context):
    """Main handler - triggered by EventBridge Scheduler every night at 11 PM."""
    print(f"Tidy-Up Agent triggered at {datetime.now().isoformat()}")

    # 1. Fetch backlog items
    items = get_backlog_items()
    print(f"Found {len(items)} backlog items")

    # 2. Use AI to categorize and summarize
    summary = categorize_and_summarize(items)
    print("Summary generated")

    # 3. Save organized report to S3
    save_sorted_backlog(items, summary)
    print("Report saved to S3")

    # 4. Email you the digest
    send_email(summary)
    print("Email sent!")

    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "Tidy-up complete!",
            "items_processed": len(items),
            "timestamp": datetime.now().isoformat()
        })
    }
